### ISSUE TITLE
Add data middle-man to to make entries data structure more flexible and prepare for senses

### ISSUE THREAD

**Issue by jacob-8** [livingtongues/living-dictionaries#274]
entries with old formats are

-> converted to current database format

entries with current database format (now includes converted old formats as well) are

-> expanded into desired shape for site usage
-> data that displays based on language (semantic domains, parts of speech) is converted into the current language

entries are easily usable and uniform in shape

When saving, save using the specific field's database format and not the expanded format.

- [x] Create above converters #275 

---

- [x] Update Algolia functions to use old or new format, spread sense down into root level #284

---

- [x] Apply convert_entry_to_current_shape and expand_entry to incoming entries using spread operation to keep old shape #291

---

- [x] export/+page.svelte entries use convert_entry_to_current_shape and expand_entry. Tthere's no need to handle multiple senses, multiple audio files, etc... as we don't yet support those but you do need to be exporting from the new fields before we can do the big refactor - #302

---

- [x] #343

**Comment by jacob-8** [comment]
TODO: use facets on things like parts of speech once they are in the sense array, we can declare the attribute for faceting as sn.ps as algolia automatically flattens the array into one object https://discourse.algolia.com/t/algoliahelper-how-to-facet-filter-a-nested-array-property/8036

**Comment by jacob-8** [comment]
TODO: handle speakerName as a facet in a situation with multiple audio files
